server:
  port: 9093
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Customer-service
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Answer-service